default: &default
  adapter: postgresql
  pool: 100
  timeout: 5000

development:
  <<: *default
  database: kudzu_development

test:
  <<: *default
  database: kudzu_test
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: kudzu_production
